### ISSUE TITLE
Using @ vite alias causes import resolution to fail

### ISSUE THREAD

**Issue by skhrvg** [WebsiteBeaver/vue-magnifier#1]
Hi! I'm using the @ vite alias in my project (which is the default one btw) and it overlaps with your alias. My guess is that the problem is with the `'@/css/style.css' `import line in `install.ts` file, because that's the only import that leaves the @ alias unchanged after compilation. You can see the error `Failed to resolve import "path_to_my_project/src/css/style.css" from "node_modules/.vite/deps/@websitebeaver_vue-magnifier.js?v=9e4030c4".` in the screenshot below.

<img width="896" alt="Снимок экрана 2023-01-08 в 14 22 16" src="https://user-images.githubusercontent.com/35118149/211193385-6a4593ef-7240-47ed-8017-f1d55b36ecd1.png">

Also, pay attention to the fact that this css file is not included in the built library after compilation.

![Снимок экрана 2023-01-08 в 14 36 16](https://user-images.githubusercontent.com/35118149/211194009-c1be62fc-143c-48bd-95a1-77d24a212f4b.png)

**Comment by skhrvg** [comment]
As a workaround i created `/src/css/style.css` file in my project with contents of your file and it seems to be working.

**Comment by D-Marc1** [comment]
Should be fixed in **1.0.1** as per the following commit:  b8429873ebd0069468e4906f2d53dbcaecb6bb2b.
